
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 27 18:07:28 IRST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ADDTO = 17;
  public static final int GTEQ = 25;
  public static final int OPERATION = 18;
  public static final int LTEQ = 22;
  public static final int UMINUS = 30;
  public static final int PRIVATE = 38;
  public static final int LPAREN = 10;
  public static final int SEMI = 2;
  public static final int INT = 7;
  public static final int MINUS = 29;
  public static final int STATIC = 40;
  public static final int RPAREN = 11;
  public static final int NOT = 21;
  public static final int AND = 20;
  public static final int LT = 23;
  public static final int OR = 19;
  public static final int COMMA = 3;
  public static final int CLASS = 36;
  public static final int DIV = 32;
  public static final int NUM = 43;
  public static final int PLUS = 28;
  public static final int THIS = 39;
  public static final int ID = 42;
  public static final int DOT = 4;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int RETURN = 15;
  public static final int TRUE = 34;
  public static final int NEW = 41;
  public static final int error = 1;
  public static final int EQEQ = 26;
  public static final int MOD = 33;
  public static final int VOID = 8;
  public static final int EQ = 16;
  public static final int LBRACK = 5;
  public static final int TIMES = 31;
  public static final int LBRACE = 12;
  public static final int RBRACK = 6;
  public static final int WHILE = 14;
  public static final int PUBLIC = 37;
  public static final int RBRACE = 13;
  public static final int FALSE = 35;
  public static final int GT = 24;
  public static final int NOTEQ = 27;
}

